name: Build and run
env:
    isSolutionFileExist :  false
    isTestFileExist :  false
    
on:
  # Triggers the workflow on  pull request events 
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Unit-tests:
    # Use the latest version of Windows as the runner
    runs-on: windows-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      # Checkout the repository to the runner
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Set up the .NET environment
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:        
          # Replace with the desired .NET Core version
          dotnet-version: "7.0.x"       
              
      - name: Build all solutions
        run: |
          # The starting directory for iteration
          starting_directory="./"
          
          # Function to find all the .sln files in the directory
          find_sln_files_to_build() {
            for file in "$1"/*; do
                  if [ -d "$file" ]; then
                    find_sln_files_to_build "$file"
                  elif [ "${file##*.}" = "sln" ]; then
                    isSolutionFileExist=true
                    echo -e "\n\nFound .sln file: $file" 
                    dotnet restore "$file"
                    dotnet build --configuration Release "$file"
                  fi
            done
          }
          #Calling  find_sln_files_to_build function with input parameter starting_directory
          find_sln_files_to_build "$starting_directory"
          
          # If no solution file is found display "No solution files found to build"           
          if [ "$isSolutionFileExist" == "false" ]
           then
              echo "No solution files found to build"
          fi 
        shell: bash 
          
          
      - name: Run unit tests inside "UnitTest" directory
        run: |
          # The starting directory for iteration
          starting_directory="./Tests/Unit_Test"
          
          # Function to find .sln files
          find_sln_files() {
            for file in "$1"/*; do
              if [ -d "$file" ]; then
                find_sln_files "$file"
              elif [ "${file##*.}" = "sln" ]; then
                isTestFileExist=true
                echo -e "\n\nFound .sln file: $file"
                echo "Running unit test file $file"
                dotnet test "$file"                
              fi
            done
          }
          
          #Calling  find_sln_files_to_build function with input parameter starting_directory
          find_sln_files "$starting_directory"
           
          # If no solution file is found display "No test files found" 
          if [ "$isTestFileExist" == "false" ]
           then
              echo "No test files found"
          fi
        shell: bash
