name: Run Unit Test
env:
    # Replace with your solution location
    solution_file_location: ./Calculator_Demo/Calculator_Demo.sln
    # Replace with the desired .NET Core version
    dotnetVersion : 7.0.x  
    isFileExist :  false
    
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Unit-tests:
    # Use the latest version of Ubuntu as the runner
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the runner
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Set up the .NET environment
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:         
          dotnet-version: " 7.0.x"           
      
      # Restore the project dependencies   
      - name: Restore dependencies
        run: dotnet restore "$solution_file_location"
        
      # Build the project in Release configuration
      - name: Build project
        run: dotnet build --configuration Release "$solution_file_location"
     
      # Run unit test
      - name: Run unit tests inside folder "UnitTest"
        run: |
          # The starting directory for iteration
          starting_directory="UnitTest"
          # Function to find .sln files
          find_sln_files() {
            for file in "$1"/*; do
              if [ -d "$file" ]; then
                find_sln_files "$file"
              elif [ "${file##*.}" = "sln" ]; then
                isFileExist=true
                echo -e "\n\nFound .sln file: $file"
                echo "Running unit test file $file"
                dotnet test "$file"                
              fi
            done
          }
          find_sln_files "$starting_directory"
                    
          if [ "$isFileExist" == "false" ]
           then
              echo "No test files found"
          fi
            echo "$isFileExist"
